# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
dist: trusty
sudo: required
cache: packages

before_install:
  sudo apt-get install -y libprotobuf-dev protobuf-compiler

r: bioc-devel

r_github_packages:
 - hadley/devtools#1263
 - Bioconductor-mirror/zlibbioc
 - Bioconductor-mirror/rhdf5
 - rte-antares-rpackage/manipulateWidget@develop
 - rte-antares-rpackage/antaresMaps
 - rte-antares-rpackage/antaresRead@develop
 - rte-antares-rpackage/antaresProcessing@develop

addons:
  apt:
    sources:
      - sourceline: 'ppa:opencpu/jq'
    packages:
      - libjq-dev
      - valgrind
      - libgdal-dev
      - libproj-dev
      - libv8-3.14-dev
      
include:
  - r: release
  - r: oldrel
  - r: devel

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'