# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
dist: trusty
sudo: required
cache: packages

addons:
  apt:
    packages:
      - libgdal-dev
      - libproj-dev
      - libv8-3.14-dev

include:
  - r: release
  - r: oldrel
  - r: devel

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'