# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
dist: trusty
sudo: required
cache: packages



bioc_required: true
bioc_use_devel: true

os:
 - linux
 - osx


r:
 - oldrel
 - release
 - devel

r_packages:
  - covr
  - devtools
  - antaresProcessing

r_github_packages:
 - Bioconductor-mirror/zlibbioc
 - Bioconductor-mirror/rhdf5
 - rte-antares-rpackage/manipulateWidget@develop
 - rte-antares-rpackage/antaresMaps
 - rte-antares-rpackage/antaresRead@develop
 - rte-antares-rpackage/antaresProcessing@develop

addons:
  apt:
    sources:
      - sourceline: 'ppa:opencpu/jq'
    packages:
      - libjq-dev
      - valgrind
      - libgdal-dev
      - libproj-dev
      - libv8-3.14-dev

  
after_success:
  - Rscript -e 'library(covr); codecov()'