# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
dist: trusty
sudo: required
cache: packages



bioc_required: true
bioc_use_devel: true

os:
 - linux
 - osx


r:
 - oldrel
 - release
 - devel

r_packages:
  - covr
  - devtools
  - antaresProcessing

r_github_packages:
 - Bioconductor-mirror/zlibbioc
 - Bioconductor-mirror/rhdf5
 - rte-antares-rpackage/manipulateWidget@master
 - rte-antares-rpackage/antaresMaps@develop
 - rte-antares-rpackage/antaresRead@develop
 - rte-antares-rpackage/antaresProcessing@develop

addons:
  apt:
    sources:
      - sourceline: 'ppa:opencpu/jq'
    packages:
      - libjq-dev
      - valgrind
      - libv8-3.14-dev
      - libudunits2-dev
      - libprotobuf-dev
      - protobuf-compiler

before_install:
  - export CURWD=`pwd`
  - sudo apt-get install libproj-dev libgeos++-dev
  - cd
  - wget http://download.osgeo.org/gdal/2.1.0/gdal-2.1.0.tar.gz
  - tar zxf gdal-2.1.0.tar.gz
  - cd gdal-2.1.0
  - ./configure
  - make
  - sudo make install
  - cd
  - wget http://download.osgeo.org/proj/proj-4.9.3.tar.gz
  - tar zxvf proj-4.9.3.tar.gz
  - cd proj-4.9.3
  - ./configure
  - make
  - sudo make install
  - sudo ldconfig
  - cd $CURWD
  
after_success:
  - Rscript -e 'library(covr); codecov()'