# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

cache: bundler

install:
  ps: Bootstrap

# Adapt as necessary starting from here

environment:
  matrix:
  - R_VERSION: release
    R_ARCH: x64
    USE_RTOOLS: true

  - R_VERSION: patched
    USE_RTOOLS: true
    
  - R_VERSION: devel
    GCC_PATH: mingw_32
    USE_RTOOLS: true
    CRAN: http://cran.rstudio.com

  - R_VERSION: devel
    R_ARCH: x64
    GCC_PATH: mingw_64
    USE_RTOOLS: true

  - R_VERSION: stable
    USE_RTOOLS: true

build_script:
  - travis-tool.sh install_deps
  #before 
  #- travis-tool.sh install_bioc zlibbioc
  #- travis-tool.sh install_bioc rhdf5
  #after "'BiocInstaller' and 'biocLite()' are deprecated, use the 'BiocManager' CRAN"
  - travis-tool.sh install_bioc_deps
  - ./travis-tool.sh install_github rte-antares-rpackage/antaresProcessing@develop
  - ./travis-tool.sh install_github rte-antares-rpackage/antaresRead@develop
  - set _R_CHECK_FORCE_SUGGESTS_=false
  #- ./travis-tool.sh install_github tidyverse/tidyselect 
  #- ./travis-tool.sh install_github rte-antares-rpackage/antaresMaps@develop
  #- ./travis-tool.sh install_github rte-antares-rpackage/leaflet.minicharts
#  - ./travis-tool.sh install_github rte-antares-rpackage/manipulateWidget@master

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
